version: '3.9'

services:
  web:
    container_name: ${APP_CONTAINER_NAME:-yuno-app-container}
    build:
      context: ./src
      dockerfile: ./Dockerfile
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8070:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - ./src/.env
    depends_on:
      - yuno-db

  yuno-db:
    container_name: ${DB_CONTAINER_NAME:-yuno-db-container}
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./src/.env
    environment:
      - POSTGRES_DB=${DB_NAME:-db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}

volumes:
  postgres_data:
