version: "3.9"

services:
  web:
    container_name: ${APP_CONTAINER_NAME:-yuno-app-container}
    build:
      context: ./src
      dockerfile: ./compose/local/Dockerfile
    command: /start
    restart: unless-stopped
    volumes:
      - ./src:/usr/src
    ports:
      - "8070:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: ${DB_CONTAINER_NAME:-yuno-db-container}
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-db}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-server:
    container_name: ${REDIS_CONTAINER_NAME:-yuno-redis-container}
    image: "redis:alpine"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=no

  minio:
    container_name: ${MINIO_CONTAINER_NAME:-yuno-minio-container}
    image: minio/minio:latest
    command: "server /data --console-address ':9001'"
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  celery-worker:
    container_name: ${CELERY_WORKER_CONTAINER_NAME:-yuno-celery-worker-container}
    build:
      context: ./src
      dockerfile: ./compose/local/Dockerfile
    command: /start-celeryworker
    volumes:
      - ./src:/usr/src
    env_file:
      - .env
    depends_on:
      - redis-server
      - db

  flower:
    container_name: ${FLOWER_CONTAINER_NAME:-yuno-flower-container}
    build:
      context: ./src
      dockerfile: ./compose/local/Dockerfile
    command: /start-flower
    volumes:
      - ./src:/usr/src
    env_file:
      - .env
    ports:
      - "5557:5555"
    depends_on:
      - redis-server
      - db

volumes:
  postgres_data:
