version: '3.9'

services:
  web:
    container_name: ${APP_CONTAINER_NAME:-yuno-app-container}
    build:
      context: ./src
      dockerfile: ./Dockerfile
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8070:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - ./src/.env
    depends_on:
      - yuno-db

  yuno-db:
    container_name: ${DB_CONTAINER_NAME:-yuno-db-container}
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-db}

  redis-server:
    container_name: ${REDIS_CONTAINER_NAME:-yuno-pgadmin-container}
    image: "redis:alpine"
    restart: unless-stopped
    expose:
      - "6379"
    env_file:
      - ./src/.env
    environment:
      - REDIS_MASTER_HOST=${REDIS_HOST:-redis-server}
      - REDIS_MASTER_PORT_NUMBER=${REDIS_PORT:-6379}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD:-my_master_password}

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME:-yuno-pgadmin-container}
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: admin@axelm.space
       PGADMIN_DEFAULT_PASSWORD: password_1337!
       PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - yuno-db


volumes:
  postgres_data:
  pgadmin:
