version: "3.9"

services:
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 15432:15432
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password_1337!
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 15432
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '${DB_HOST}:${DB_PORT}:*:${DB_USER}:${DB_PASSWORD}' > /tmp/pgpassfile && /entrypoint.sh"

volumes:
  pgadmin_data:
