"""empty message

Revision ID: a1365fc39f95
Revises: 2f579bca7ed2
Create Date: 2022-12-16 17:43:08.327364

"""
import sqlalchemy as sa
import sqlmodel  # added

from alembic import op

# revision identifiers, used by Alembic.
revision = "a1365fc39f95"
down_revision = "2f579bca7ed2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, "User", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="unique")
    op.drop_column("User", "username")
    # ### end Alembic commands ###
