"""empty message

Revision ID: 77e0988e752b
Revises: 169267038d18
Create Date: 2022-12-10 13:55:17.175113

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "77e0988e752b"
down_revision = "169267038d18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("role_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "User", "Role", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="foreignkey")
    op.drop_column("User", "role_id")
    # ### end Alembic commands ###
