"""empty message

Revision ID: 1b328c7c4f0f
Revises: 59a400324b45
Create Date: 2023-01-11 20:38:36.247186

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b328c7c4f0f"
down_revision = "59a400324b45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ProjectUsers_id", table_name="ProjectUsers")
    op.drop_column("ProjectUsers", "id")
    op.drop_column("ProjectUsers", "created_at")
    op.drop_column("ProjectUsers", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ProjectUsers",
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ProjectUsers",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ProjectUsers", sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False)
    )
    op.create_index("ix_ProjectUsers_id", "ProjectUsers", ["id"], unique=False)
    # ### end Alembic commands ###
