"""empty message

Revision ID: 7f9cfb7bdf08
Revises: 3360439ada52
Create Date: 2023-02-14 10:54:01.903784

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f9cfb7bdf08"
down_revision = "3360439ada52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Project", sa.Column("percent_completed", sa.Float(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Project", "percent_completed")
    # ### end Alembic commands ###
