"""empty message

Revision ID: 2ffa84639104
Revises: 27ef60460a81
Create Date: 2023-01-19 13:06:37.730101

"""
import sqlalchemy as sa
import sqlmodel  # added

from alembic import op

# revision identifiers, used by Alembic.
revision = "2ffa84639104"
down_revision = "27ef60460a81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Task", sa.Column("created_by_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "Task", "User", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Task", type_="foreignkey")
    op.drop_column("Task", "created_by_id")
    # ### end Alembic commands ###
