"""empty message

Revision ID: 2504374ce9c0
Revises: 2529154798f0
Create Date: 2023-01-12 08:48:44.538605

"""
import sqlalchemy as sa
import sqlmodel  # added

from alembic import op

# revision identifiers, used by Alembic.
revision = "2504374ce9c0"
down_revision = "2529154798f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Project", sa.Column("created_by_id", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "Project", "User", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Project", type_="foreignkey")
    op.drop_column("Project", "created_by_id")
    # ### end Alembic commands ###
