"""empty message

Revision ID: d5e83d0242cb
Revises: 2504374ce9c0
Create Date: 2023-01-12 09:43:28.966787

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5e83d0242cb"
down_revision = "2504374ce9c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Project_created_by_id_fkey", "Project", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "Project_created_by_id_fkey", "Project", "User", ["created_by_id"], ["id"]
    )
    # ### end Alembic commands ###
