"""empty message

Revision ID: 3360439ada52
Revises: 2ffa84639104
Create Date: 2023-01-30 15:32:14.099667

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3360439ada52"
down_revision = "2ffa84639104"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Project_created_by_id_fkey", "Project", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "Project_created_by_id_fkey", "Project", "User", ["created_by_id"], ["id"]
    )
    # ### end Alembic commands ###
