"""empty message

Revision ID: 40068ac95f4d
Revises: 1b328c7c4f0f
Create Date: 2023-01-11 21:02:02.520609

"""
import sqlalchemy as sa
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "40068ac95f4d"
down_revision = "1b328c7c4f0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ProjectUsersLink",
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.drop_table("ProjectUsers")
    op.drop_constraint("Project_created_by_id_fkey", "Project", type_="foreignkey")
    op.drop_column("Project", "created_by_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Project",
        sa.Column("created_by_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "Project_created_by_id_fkey", "Project", "User", ["created_by_id"], ["id"]
    )
    op.create_table(
        "ProjectUsers",
        sa.Column("project_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("joined_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["Project.id"], name="ProjectUsers_project_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], name="ProjectUsers_user_id_fkey"),
    )
    op.drop_table("ProjectUsersLink")
    # ### end Alembic commands ###
