[tool.poetry]
name = "yuno"
version = "0.1.0"
description = "Task management backend service"
authors = ["8thgencore <8th@example.com>"]

[tool.black]
line-length = 99
target-version = [ "py37", "py38", "py39", "py310"]
exclude = "((.eggs | .git | .pytest_cache | build | dist))"

[tool.ruff]
line-length = 99
exclude = [".git", "__pycache__", ".mypy_cache", ".pytest_cache"]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = [    
    "B904",
    "B006",    
    "E501",  # line too long, handled by black
    "E712",  # in sqlmodel better used ==
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.92.0"}
alembic = "^1.9.4"
asyncpg = "^0.27.0"
passlib = "^1.7.4"
sqlmodel = "^0.0.8"
fastapi-async-sqlalchemy = "^0.3.12"
fastapi-cache2 = {extras = ["redis"], version = "^0.2.1"}
fastapi-pagination = {extras = ["sqlalchemy"], version = "^0.11.4"}
minio = "^7.1.13"
Pillow = "^9.4.0"
watchfiles = "^0.18.1"
redis = "^4.5.1"
celery = "^5.2.7"
flower = "^1.2.0"
fastapi-mail = "^1.2.5"

[tool.poetry.dev-dependencies]
mypy = "^1.0.1"
yesqa = "^1.4.0"
httpx = "^0.23.3"
pytest = "^7.2.1"
black = "^23.1.0"
ruff = "^0.0.245"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
